version: "3.8"
services:
  mongo:
    image: mongo:7
    container_name: helma-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: helma
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
