package com.backend.helmaaibackend.domain;

public enum AuditType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    USER_DEACTIVATE_SELF,
    ADMIN_DEACTIVATE,
    ADMIN_SOFT_DELETE,
    ADMIN_HARD_DELETE,
    ADMIN_RESTORE,
    ADMIN_UPDATE_ROLES,
    ADMIN_UPDATE_STATUS,
    ANNOUNCEMENT_CREATE,
    EMERGENCY_TRIGGER,
    EMERGENCY_CONTACT_NOTIFY,
    ERROR
}
